const { chromium } = require('playwright');

const urls = [
  'https://sanand0.github.io/tdsdata/js_table/?seed=82',
  'https://sanand0.github.io/tdsdata/js_table/?seed=83',
  'https://sanand0.github.io/tdsdata/js_table/?seed=84',
  'https://sanand0.github.io/tdsdata/js_table/?seed=85',
  'https://sanand0.github.io/tdsdata/js_table/?seed=86',
  'https://sanand0.github.io/tdsdata/js_table/?seed=87',
  'https://sanand0.github.io/tdsdata/js_table/?seed=88',
  'https://sanand0.github.io/tdsdata/js_table/?seed=89',
  'https://sanand0.github.io/tdsdata/js_table/?seed=90',
  'https://sanand0.github.io/tdsdata/js_table/?seed=91',
];

(async () => {
  // Launch a headless (invisible) browser
  const browser = await chromium.launch();
  const page = await browser.newPage();

  let grandTotal = 0;

  for (const url of urls) {
    // Go to the page and wait until the network is idle
    // (important! these tables are dynamically generated by JavaScript)
    await page.goto(url, { waitUntil: 'networkidle' });

    // Wait for at least one table cell to appear
    await page.waitForSelector('td');

    // Grab all text from all <td> cells, parse as numbers, and sum them
    const pageSum = await page.evaluate(() => {
      const cells = document.querySelectorAll('td');
      let sum = 0;
      cells.forEach(cell => {
        const value = parseFloat(cell.innerText);
        if (!isNaN(value)) {
          sum += value;
        }
      });
      return sum;
    });

    console.log(`Sum for ${url}: ${pageSum}`);
    grandTotal += pageSum;
  }

  console.log(`Total sum across all pages: ${grandTotal}`);

  await browser.close();
})();
